# Generated by Django 4.0.5 on 2023-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('contact_no', models.CharField(max_length=200, verbose_name='')),
                ('contact_no2', models.CharField(blank=True, max_length=200, verbose_name='')),
                ('email', models.EmailField(max_length=200)),
                ('postal_add', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('municipality', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=200, null='True')),
                ('department', models.CharField(blank=True, max_length=200)),
                ('profileimg', models.ImageField(blank=True, default='blank-profile-picture.png', null='True', upload_to='profile_images')),
                ('website', models.URLField(blank=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
