# Generated by Django 3.2.6 on 2023-06-14 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
