# Generated by Django 3.2.6 on 2023-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='suburb',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
