# Generated by Django 4.0.5 on 2023-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230706_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='suburb',
            new_name='town',
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='province',
            field=models.CharField(choices=[('GP', 'GAUTENG'), ('EC', 'EASTERN CAPE'), ('WC', 'WESTERN CAPE'), ('NC', 'NORTHERN CAPE'), ('L', 'LIMPOPO'), ('MP', 'MPUMALANGA'), ('NW', 'NORTH WEST'), ('KZ', 'KWAZULU NATAL'), ('FS', 'FREE STATE')], default='GP', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
