# Generated by Django 4.0.5 on 2023-07-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_suburb_entity_town_alter_entity_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contact_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_no2',
            field=models.CharField(blank=True, max_length=200, verbose_name='contact 2'),
        ),
    ]
