# Generated by Django 4.0.5 on 2023-07-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_entity_contact_no_alter_entity_contact_no2'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.TextField(blank=True, default='Hospital'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
