# Generated by Django 4.0.5 on 2023-07-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_entity_gps_coordinates_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
