# Generated by Django 4.0.5 on 2023-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_entity_area_alter_entity_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.TextField(blank=True, choices=[('Hospital', 'HOSPITAL'), ('School', 'SCHOOL'), ('Clinic', 'CLINIC'), ('Police Station', 'POLICE STATION'), ('Municipal Office', 'MUNICIPAL OFFICE'), ('Utility', 'UTILITY')]),
        ),
    ]
