# Generated by Django 4.0.5 on 2023-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_entity_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.AlterField(
            model_name='entity',
            name='profileimg',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_images'),
        ),
    ]
