# Generated by Django 4.0.5 on 2023-05-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicentity_delete_entity_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reveiw',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Curator_Profile',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
