# Generated by Django 4.0.5 on 2023-08-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicEntity',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='first_name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
