# Generated by Django 4.0.5 on 2023-08-18 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_publicentity_remove_user_profile_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='id_user',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
